# Generated by Django 5.1.4 on 2025-05-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarea_priodad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='priodad',
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=5),
        ),
    ]
